### ISSUE TITLE
There is a better way to do this, I believe

### ISSUE THREAD

**Issue by adriatic** [MaximBalaganskiy/AureliaDotnetTemplate#1]
Hi, @MaximBalaganskiy 

You may or may not be aware of the AUCS project that started with a lot of enthusiasm, 25 people stated their intent to collaborate, but then got deflated for many reasons that I do not want to share in such public way.

I created a new organization - **[longarone](https://github.com/longarone)** which should deliver on AUCS promises. The difference is in my approach: instead of asking people to spend the time on creating the necessary tooling, build environment for both code and guides, I am doing all that myself. At the moment, I do have a few things to show - see **[](https://github.com/longarone/code-samples)**:

- all **[basic](https://github.com/longarone/code-samples/tree/master/basic)** samples are created by CLI build tooling.
- the sample you call AureliaDotNet Template fits better in the **[full stack collection](https://github.com/longarone/code-samples/tree/master/full-stack)**, where the app is built as two separated projects (one with Aurelia CLI and the other with dotnet CLI). Such model will allow us to illustrate the development of the more complex full stack applications, so this skeleton and its "cousins" serve as introduction in more complex applications - see **[this](https://github.com/longarone/code-samples/issues/8#issue-311017447)** for more information 

Not all samples are finished or properly documented, so I am only trying to get you interested to participate in Longarone, rather than the "we all do our own stuff" effort. 

If you want to find out more, please ask 😄

**Comment by adriatic** [comment]
@lancescole As always, the assessment is in the "eye of the beholder". My view is derived from the intent to create a set of generic guides for full stack applications development covering many different front ends combined with many different back ends. You seem to prefer a lot more specific context, so this template serves you well.

**Comment by PeterWone** [comment]
A virtue of Aurelia is that it is trivial to lift the SPA portion out. I'm with @lancescole on this; nearly all my projects are hosted on IIS and use MSSQL via web services and LINQ on EF core. If I wanted to target something else all I'd need to do is ignore the controllers and use another URL in my fetches.

**Comment by adriatic** [comment]
@PeterWone it would be hard to disagree with your explanation, particularly since you "speak" from experience (and so does, @lancescole, by the way).

My view comes from the position that there is no reason to keep all parts of a distributed application in the same project, particularly of there is more than one developer than works on this. Clearly, my position is no more "right" than @lancescole (_.. but in our case, there would be nothing to gain._), so this is a purely academic discussion that does not contribute much to the world 😄

**Comment by PeterWone** [comment]
@adriatic the point of my observation is that a template like this one is better for a common use case, and no worse for the general case.

**Comment by adriatic** [comment]
Since I started this discussion and because I think that there is no reason to discuss it any further, I am proposing to close it.
