### ISSUE TITLE
Shouldn't the router be of type AppRouter instead of Router ?

### ISSUE THREAD

**Issue by gcastre** [MaximBalaganskiy/AureliaDotnetTemplate#10]
Because it is the main router and so you cannot use some function like Deactivate()

https://github.com/MaximBalaganskiy/AureliaDotnetTemplate/blob/master/ClientApp/app/components/app/app.ts#L5

Definition ref:

https://github.com/aurelia/router/blob/master/dist/aurelia-router.d.ts#L875-L906

**Comment by MaximBalaganskiy** [comment]
The signature is copied from
https://aurelia.io/docs/routing/configuration#basic-configuration
Never had any problems with it...
