### ISSUE TITLE
Adding i18n

### ISSUE THREAD

**Issue by gcastre** [MaximBalaganskiy/AureliaDotnetTemplate#11]
Hello,

I tried to add aurelia-i18n and I have a problem with webpack, I followed the documentation, and everything works fine except when I edit a file that trigger the webpack watch.

When I launch the first time, my translation.json are copied to a locales folder inside the dist but when the watch triggers it remove the translation.json without re-copying them.

Here is how I configured the locales copy:

```
plugins: [
	new CleanWebpackPlugin(),
	new webpack.DefinePlugin({ IS_DEV_BUILD: JSON.stringify(isDevBuild) }),
	new webpack.ProvidePlugin({ $: "jquery", jQuery: "jquery", "window.jQuery": "jquery" }),
	new HtmlWebpackPlugin({ template: 'index.ejs', filename: "../../wwwroot/index.html", inject: false, metadata: {}, alwaysWriteToDisk: true }),
	new AureliaPlugin({ aureliaApp: "boot" }),
	new GlobDependenciesPlugin({ "boot": ["ClientApp/**/*.{ts,html}"] }),
	new ModuleDependenciesPlugin({}),
	new MiniCssExtractPlugin({
		filename: "[name].[hash].css",
		chunkFilename: "[name].[chunkhash].css"
	}),
	new CopyWebpackPlugin([
		{ from: 'ClientApp/app/locales/', to: 'locales/' }
	]),
],
```

I don't know why the CopyWebpackPlugin don't trigger when the watch is called. Do you have any idea why ?

Thanks.

**Comment by gcastre** [comment]
Ok after a bit of digging you have to add

```
	new CleanWebpackPlugin({
		cleanAfterEveryBuildPatterns: ['!**/locales/**/translation.json'],
	}),
```

Sorry i've never played with webpack, should have done better research before posting !

**Comment by MaximBalaganskiy** [comment]
You might want to have a look
https://github.com/webpack-contrib/copy-webpack-plugin/issues/252
