### ISSUE TITLE
Upgrading to Dotnet Core 3..

### ISSUE THREAD

**Issue by si2030** [MaximBalaganskiy/AureliaDotnetTemplate#7]
Any chance of upgrading this to dotnet core 3.0? Cheers Simon

**Comment by MaximBalaganskiy** [comment]
Yeah, why not... Maybe this week I'll have some time

**Comment by si2030** [comment]
Awesome.

**Comment by si2030** [comment]
Thanks Max appreciated.

**Comment by MaximBalaganskiy** [comment]
Mind you, there's been a change in the development flow - no more spa services
