### ISSUE TITLE
Getting an error on Boot.ts

### ISSUE THREAD

**Issue by si2030** [MaximBalaganskiy/AureliaDotnetTemplate#8]
On the off chance you are watching this I am getting the following error in the console:

`TypeError: Cannot read property 'href' of undefined
    at boot.ts:35
    at HttpClient.push../node_modules/aurelia-fetch-client/dist/native-modules/aurelia-fetch-client.js.HttpClient.configure (aurelia-fetch-client.js:160)
    at Module.configure (boot.ts:34)
    at aurelia-bootstrapper.js:128`

 in which is failing on this line in boot.ts

`    new HttpClient().configure(config => {
        const baseUrl = document.getElementsByTagName("base")[0].href;
        config.withBaseUrl(baseUrl);
    });`

This was commented out in the template but worked in the old version for me.. any chance you might know the reason for the error? Regards Simon

**Comment by MaximBalaganskiy** [comment]
There's no base element in the new template, that commented code should be
deleted

**Comment by si2030** [comment]
Its come up.. teething problems.. Thanks for responding again.. 

I had it uncommented on my original.. and I did comment it out.. is it that I dont actually need it now..

**Comment by MaximBalaganskiy** [comment]
There was an issue with publicPath in previous webpack config which that code solved. Absolute path didn't work well with virtual directories. I now changed the path to relative and this fix to copy ~ to http client is not needed.

**Comment by si2030** [comment]
Thanks Maxx
